import type { Representative } from "@/types/representative";

export const REPRESENTATIVES_DATA: Representative[] = [
  {
    slug: "hajj-lead-scholar-placeholder",
    name: "[Placeholder] Lead Scholar Guide",
    role: "Islamic Scholar & Hajj Guide",
    bio: "Unconfirmed. Lead scholar responsible for conducting fiqh seminars and guiding pilgrims step-by-step through Hajj rituals.",
    imageUrl: null,
    videoUrl: null,
    phone: null,
    email: null,
    departmentSlug: "hajj",
    isScholar: true,
    active: true,
    featured: true,
    displayOrder: 1,
  },
  {
    slug: "umrah-scholar-guide-placeholder",
    name: "[Placeholder] Scholar Guide",
    role: "Umrah Spiritual Guide",
    bio: "Unconfirmed. Resident scholar providing daily spiritual talks and leading group prayers in Makkah and Madinah.",
    imageUrl: null,
    videoUrl: null,
    phone: null,
    email: null,
    departmentSlug: "umrah",
    isScholar: true,
    active: true,
    featured: true,
    displayOrder: 2,
  },
  {
    slug: "customer-relations-lead-placeholder",
    name: "[Placeholder] Customer Service Lead",
    role: "Support Lead",
    bio: "Unconfirmed. Manages client documentation, visa confirmation, and hotel check-in coordinates.",
    imageUrl: null,
    videoUrl: null,
    phone: null,
    email: null,
    departmentSlug: "logistics",
    isScholar: false,
    active: true,
    featured: false,
    displayOrder: 3,
  },
];
